---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: yes

dotfiles_repo: git@github.com:Xixiao007/dotfiles-mac-vagrant-ubuntu.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .Xdefaults
  - .Xmodmap_vagrant
  - .editorconfig
  - .tmux.conf
  - .gitconfig
  - bg.jpg
  - .config
  # - .config/fish
  # - .config/i3
  # - .config/i3status
  - .macos

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - ssh-copy-id
  - openssl
  - wget
  - fish

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  # - homebrew/php

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - vagrant
  # need to manually install 5.1.30r118389 from vbox website. Newer version fails to install chrome and g-console :(
  # - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 419330170, name: "Moom" }
  - { id: 732710998, name: "Enpass" }
  # - { id: 784801555, name: "One Note" }
mas_email: ""
mas_password: ""

# osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
